config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'courts#index'
  resources :courts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'カテゴリー' },
    { id: 2, name: '屋内' },
    { id: 3, name: '屋外' }
  ]

  include ActiveHash::Associations
  has_many :courts

  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :court
  belongs_to :user

  validates :text, presence: true
end

app/models/court.rb
class Court < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :number
  belongs_to :prefecture

  validates :text, :image, :local, presence: true
  validates :category_id, :number_id, :prefecture_id, numericality: { other_than: 1 , message: "can't be blank"}
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ""
      Court.where('text LIKE(?)', "%#{search}%")
    else
      Court.all
    end
  end
end

app/models/number.rb
class Number < ActiveHash::Base
  self.data = [
    { id: 1, name: 'リングの数' },
    { id: 2, name: '1つ' },
    { id: 3, name: '2つ' },
    { id: 4, name: '3つ' },
    { id: 5, name: '4つ' },
    { id: 6, name: '5つ以上' }
  ]

  include ActiveHash::Associations
  has_many :courts

  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '都道府県' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :courts

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :courts
  has_many :comments

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/courts/#{comment.court.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, court_id: params[:court_id])
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:edit, :show, :update]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :search_court, only: [:index, :search]

  def index
    @courts = Court.includes(:user).order("created_at DESC")
    set_court_column
  end

  def new
    @court = Court.new
  end

  def create
    @court = Court.new(court_params)
    if @court.save
      render :create
    else
      render :new
    end
  end

  def destroy
    court = Court.find(params[:id])
    court.destroy
  end

  def edit
  end

  def update
    @court.update(court_params)
    if @court.save
      render :update
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @court.comments.includes(:user)
  end

  def search
    @results = @p.result
  end

  private

  def court_params
    params.require(:court).permit(:image, :text,:category_id,:number_id,:local,:prefecture_id,:address).merge(user_id: current_user.id)
  end
  
  def set_court
    @court = Court.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def search_court
    @p = Court.ransack(params[:q])
  end

  def set_court_column
    @court_text = Court.select("text").distinct
    @court_prefecture_id = Court.select("prefecture_id").distinct
    @court_local = Court.select("local").distinct
    @court_address = Court.select("address").distinct
    @court_category_id = Court.select("category_id").distinct
    @court_number_id = Court.select("number_id").distinct
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @courts = user.courts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courts/_court.html.erb
<div class="content_post" style="background-image: url(<%= court.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', court_path(court.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == court.user_id %>
          <li>
            <%= link_to '編集', edit_court_path(court.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', court_path(court.id), method: :delete %>
          </li>
          <% end %>
        </ul>
      </div>
      <p><%= court.text %></p>
      <span class="name">
        <a href="/users/<%= court.user.id %>">
          <span>投稿者</span><%= court.user.nickname %>
        </a>
      </span>
</div>

app/views/courts/_form.html.erb
<%= form_with(model: court, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <%= f.text_field :image, placeholder: "画像のURL" %>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %>
    <%= f.text_field :local, placeholder: "市区町村" %>
    <%= f.text_field :address, placeholder: "番地以降（任意）" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
    <%= f.collection_select(:number_id, Number.all, :id, :name, {}, {class:"number-select"}) %>
    <%= f.text_field :text, placeholder: "名称", rows: "1" %>
    <%= f.submit "SEND" %>
<% end %>

app/views/courts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/courts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/courts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { court: @court } %>
  </div>
</div>

app/views/courts/index.html.erb
<%= search_form_for @p, url: search_courts_path do |f| %>
  <%= f.label :text_eq, '名称' %>
  <%= f.collection_select :text_eq, @court_text, :text, :text,  include_blank: '指定なし' %>
  <br>
  <%= f.label '都道府県' %>
  <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name,  include_blank: '指定なし' %>
  <br>
  <%= f.label :local_eq, '市区町村' %>
  <%= f.collection_select :local_eq, @court_local, :local, :local,  include_blank: '指定なし' %>
  <br>
  <%= f.label :address_eq, '番地以降' %>
  <%= f.collection_select :address_eq, @court_address, :address, :address,  include_blank: '指定なし' %>
  <br>
  <%= f.label 'カテゴリー' %>
  <%= f.collection_select :category_id_eq, Category.all, :id, :name,  include_blank: '指定なし' %>
  <br>
  <%= f.label 'リングの数' %>
  <%= f.collection_select :number_id_eq, Number.all, :id, :name,  include_blank: '指定なし' %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<div class="contents row">
  <% @courts.each do |court| %>
    <%= render partial: "court", locals: { court: court } %>
  <% end %>
</div>

app/views/courts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { court: @court } %>
  </div>
</div>

app/views/courts/search.html.erb
<h1 class="searchresults">
  検索結果
</h1>
<% if @results.length !=0 %>
  <div class="contents row">
  <% @results.each do |court| %>
    <%= render partial: "court", locals: { court: court } %>
  <% end %>
</div>
<% else %>
  <div class="searchback">該当する場所はありません</div>
<% end %>
<br>
<div class="nav-item active">
<%= link_to 'トップページへ戻る', root_path, class: "nav-link" %>
</div>

app/views/courts/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @court.image %>);">
  <% if user_signed_in? && current_user.id == @court.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_court_path(@court.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', court_path(@court.id), method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <p><%= @court.text %></p>
    <span class="name">
      <a href="/users/<%= @court.user.id %>">
        <span>投稿者</span><%= @court.user.nickname %>
      </a>
    </span>
  </div>
      <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= @court.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">市区町村</th>
          <td class="detail-value"><%= @court.local %></td>
        </tr>
        <tr>
          <th class="detail-item">番地以降</th>
          <td class="detail-value"><%= @court.address %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @court.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">リングの数</th>
          <td class="detail-value"><%= @court.number.name %></td>
        </tr>
      </tbody>
    </table>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@court, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/courts/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourtSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">CourtSearch</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_court_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @courts.each do |court| %>
    <%= render partial: "courts/court", locals: { court: court } %>
  <% end %>
</div>